### ISSUE TITLE
Boot-Image?

### ISSUE THREAD

**Issue by ChristophHeilmann** [AaronDewes/boot.img-patcher#2]
Hi,

wo finde ich das gepatchte Boot-Image für den Tolino Vision 6?

**Comment by AaronDewes** [comment]
Ich besitze leider keine Vision 6 und es ist mir bisher nicht gefunden, einen Weg zu finden, den Vision 6 zu modden, ich werde mich aber melden, sobald ich einen habe und eine Möglichkeit zum modden gefunden habe

**Comment by ChristophHeilmann** [comment]
Ok, aber was ist dan das für ein Image: work-v6/boot-15.2.0-patched.img?

**Comment by AaronDewes** [comment]
Das ist ein angefangenes Experiment, aber mir ist keine Möglichkeit bekannt, es zu booten.

**Comment by ChristophHeilmann** [comment]
Aber es wir doch gebootet oder nicht?
fastboot boot work-v6/boot-15.2.0-patched.img

**Comment by ChristophHeilmann** [comment]
Geht es um den security patch-level?

(bullseye)root@localhost:/home/exoriente# adb shell getprop ro.build.version.release
8.1.0
(bullseye)root@localhost:/home/exoriente# adb shell getprop ro.build.version.security_patch
2018-07-05

**Comment by ChristophHeilmann** [comment]
Kennst Du den platform-code?
https://dumps.tadiphone.dev/dumps/allwinner/virgo-perf1

**Comment by AaronDewes** [comment]
Ich habe bisher keine Möglichkeit gefunden, den Vision 6 in den Fastboot-Modus zu bekommen, um das Boot.img zu starten.

**Comment by phrogg** [comment]
Ich leider auch nicht.

**Comment by ChristophHeilmann** [comment]
Huch! 

Das ist doch kein Problem.

(bullseye)root@localhost:/home/exoriente# adb reboot bootloader
(bullseye)root@localhost:/home/exoriente# fastboot devices
Android Fastboot        fastboot
(bullseye)root@localhost:/home/exoriente# fastboot reboot
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 1.060s
(bullseye)root@localhost:/home/exoriente#

**Comment by ChristophHeilmann** [comment]
Ich täusch mich wohl es gibt ja gar kein device.

**Comment by ChristophHeilmann** [comment]
Die Allwinner-Geräte melden sich anscheined alle mit dem Namen Android Fastboot fastboot siehe http://xinabox.blogspot.com/2019/12/more-a33-quad-core-32-bit-cortex-a7.html

**Comment by AaronDewes** [comment]
Das stimmt, aber das geht nur bei tolinos, bei denen man noch ADB aktivieren kann

**Comment by ChristophHeilmann** [comment]
Anscheinend hast du nicht mitbekommen, daß man ADB auch mit der Firmware 15.2.0 aktivieren kann. Die neue Ziffernfolge lautet 1123581321

**Comment by ChristophHeilmann** [comment]
Ich habe nur ein schwachbrüstiges Chromebook mit Crouton/Debian zur Verfügung und wollte jetzt nicht extra Python installieren um das Skript ausführen zu können. Zum flashen reicht ja das gepatchte Image.

**Comment by ChristophHeilmann** [comment]
Also noch einmal zusammengefaßt (siehe Eingangsfrage): ich suche ein Boot-Image für die Firmware 15.2.0, das mir permanenten Root-Zugriff verschafft. ADB und Fastboot sind bereits funktionsfähig.

**Comment by AaronDewes** [comment]
@ChristophHeilmann Habe ich wirklich nicht mitbekommen, danke!

**Comment by AaronDewes** [comment]
Dann schreibe ich dir später nochmal

**Comment by ChristophHeilmann** [comment]
Ich habe spaßeshalber einmal den adbd von der Platform mit einem Editor geöffnet und folgende Meldung gefunden:
adbd cannot run as root in production builds

Damit die ADB im Root-Modus läuft muß höchstwahrscheinlich das Environment im Debug-Menü geändert werden.

**Comment by AaronDewes** [comment]
> Damit die ADB im Root-Modus läuft muß höchstwahrscheinlich das Environment im Debug-Menü geändert werden.

Nein, das hat nur was mit ro.debuggable zu tun. Das Environment in dem Menü ist nur, welcher der Tolino-Server genutzt wird und sollte auf keinen Fall geändert werden.

Bist du auf Telegram/Signal/Session/Discord? Dann könnte ich dir eine gepatchte boot.img zum Testen senden.

**Comment by AaronDewes** [comment]
Ich dekompiliere auch später mal 15.2.6 und schaue, was die da geändert haben.

**Comment by ChristophHeilmann** [comment]
> Bist du auf Telegram/Signal/Session/Discord? Dann könnte ich dir eine gepatchte boot.img zum Testen senden.

Nein leider nicht. Die Datei ist ja nur 18 MB groß da könnte auch Email gehen.
Meine Adresse ist christoph.heilmann@gmx.de

**Comment by AaronDewes** [comment]
Okay, ich sende dir die Datei in ca. 2h zum Testen, ich weiß aber nicht, ob es funktioniert.

**Comment by ChristophHeilmann** [comment]
Kann ich das Image zum Testen mit fastboot boot test.img laden ohne es zu flashen?

**Comment by AaronDewes** [comment]
Ja, ich sende es gleich, hat leider ein bisschen länger gedauert

**Comment by ChristophHeilmann** [comment]
Du hast mir das Bootimage der Firmware 15.2.6 geschickt. Was ist der Unterschied zur Firmwareversion 15.2.0? Den Berichten zufolge soll diese durch deep sleep states die Akkulaufzeit verbessern. Wenn das so ist will die neue Firmware nicht installieren, da ich im Hintergrund Termux-Skripte am laufen habe die dadurch womöglich abgewürgt würden.

**Comment by AaronDewes** [comment]
Für das Boot-Image sollte das keinen Unterschied machen

**Comment by ChristophHeilmann** [comment]
Also kann ich das Boot-Image auch die Firmwareversion 15.2.0 verwenden?

**Comment by AaronDewes** [comment]
Ja, wenn es geht, geht es mit allen Versionen

**Comment by ChristophHeilmann** [comment]
Ok, dan kann der Stunt ja beginnen :)

**Comment by ChristophHeilmann** [comment]
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot boot boot-15.2.6-patched.img 
Sending 'boot.img' (17218 KB)                      OKAY [  0.756s]
Booting                                            OKAY [  0.000s]
Finished. Total time: 0.820s
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot reboot
< waiting for any device >
^C
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb root
adbd cannot run as root in production builds


Das habe ich befürchtet. Es gibt einen command-line parameter buildvariant. Vielleicht reicht es ja den auf userdebug zu setzen.

**Comment by AaronDewes** [comment]
Ich schaue morgen nochmal

**Comment by ChristophHeilmann** [comment]
Joa, dann bis morgen.

**Comment by ChristophHeilmann** [comment]
Ich bin mir nicht sicher ob das Booten mit dem gepatchten Image wirklich funktioniert hat. Nach der Meldung finished war das Gerät über fastboot nicht mehr ansprechbar und reagierte auf keine Eingaben. Ich mußte es von Hand neu starten wie nach einem Absturz.

**Comment by AaronDewes** [comment]
Ich habe dir nochmal ein Boot-Iage per E-Mail geschickt, das sollte besser funktionieren.

**Comment by ChristophHeilmann** [comment]
Nein, das Image bootet nicht. 

(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot boot boot-15.2.0-patched.img
Sending 'boot.img' (17210 KB)                      OKAY [  0.779s]
Booting                                            OKAY [  0.000s]
Finished. Total time: 0.849s

**Comment by ChristophHeilmann** [comment]
Das sind die Partitionen auf dem Gerät:


03-13 21:42:25.084  1586  1587 V vold    : PART 1 0FC63DAF-8483-4772-8E79-3D69D8477DE4 12FBDE9F-05EC-4FAF-91B4-448619F701A9 UDISK
03-13 21:42:25.084  1586  1587 V vold    : 
03-13 21:42:25.084  1586  1587 V vold    : PART 2 0FC63DAF-8483-4772-8E79-3D69D8477DE4 15B9A161-767E-467D-9EDA-98D2B499C0B8 bootloader
03-13 21:42:25.084  1586  1587 V vold    : 
03-13 21:42:25.084  1586  1587 V vold    : PART 3 0FC63DAF-8483-4772-8E79-3D69D8477DE4 FECDF77C-ED56-42FE-B9F5-C0A1A25EA0E6 env
03-13 21:42:25.084  1586  1587 V vold    : 
03-13 21:42:25.084  1586  1587 V vold    : PART 4 0FC63DAF-8483-4772-8E79-3D69D8477DE4 4283CFD8-948E-4F91-8252-A4A13E896569 boot
03-13 21:42:25.084  1586  1587 V vold    : 
03-13 21:42:25.084  1586  1587 V vold    : PART 5 0FC63DAF-8483-4772-8E79-3D69D8477DE4 9532650E-CD3E-4D82-9AFC-C5D9868B3ECD system
03-13 21:42:25.084  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 6 0FC63DAF-8483-4772-8E79-3D69D8477DE4 A6CE4A79-3F2B-4FE8-8692-A44A453FDE82 vendor
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 7 0FC63DAF-8483-4772-8E79-3D69D8477DE4 24848A96-1635-4D15-8708-DF8BA0B4BB5B misc
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 8 0FC63DAF-8483-4772-8E79-3D69D8477DE4 4E258AC5-6962-4352-B2EC-6495A212C997 recovery
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 9 0FC63DAF-8483-4772-8E79-3D69D8477DE4 0CEABB70-6E72-45E0-9016-36CDEB09A242 cache
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 10 0FC63DAF-8483-4772-8E79-3D69D8477DE4 267EC007-03C5-4A0E-B813-3A05EF6D9613 metadata
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 11 0FC63DAF-8483-4772-8E79-3D69D8477DE4 C34FDE6B-6259-40CF-B211-E4410F111BAD private
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 12 0FC63DAF-8483-4772-8E79-3D69D8477DE4 B08CC69B-4E1F-4581-833A-23AC10BC44B8 frp
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 13 0FC63DAF-8483-4772-8E79-3D69D8477DE4 173B7D49-8DE3-4AA9-B18C-9496550B0989 empty
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 14 0FC63DAF-8483-4772-8E79-3D69D8477DE4 850117CF-51BF-401B-9894-358D3A7CCE81 dto
03-13 21:42:25.085  1586  1587 V vold    : 
03-13 21:42:25.085  1586  1587 V vold    : PART 15 0FC63DAF-8483-4772-8E79-3D69D8477DE4 C28663B8-935C-43A7-AB71-808D5349B479 media_data

**Comment by ChristophHeilmann** [comment]
ist der bootloader nun offen oder nicht?

(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb reboot bootloader
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot devices
Android Fastboot        fastboot
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot oem unlock
                                                   FAILED (remote: 'the requst is invalid')
fastboot: error: Command failed

**Comment by ChristophHeilmann** [comment]
Heute ist das Image bessser gelaunt, es bootet doch ;)

Allerdings ist die Fehlermeldung dieselbe wie zuvor:

(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb root
adbd cannot run as root in production builds

In der command line muß die buildvariant userdebug heißen und nicht user:


Build: .8af4a07 20211124-163439
Build fingerprint: 'RakutenKobo/E70P14_android/E70P14_android:8.1.0/8af4a07/20211124-163439:user/release-keys'
Bootloader: unknown
Radio: (unknown)
Network: (unknown)
Kernel: Linux version 4.9.56 (root@runner-4w1nqxi2-project-434-concurrent-0) (gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) ) #1 SMP PREEMPT Wed Nov 24 16:33:36 UTC 2021
Command line: earlyprintk=sunxi-uart,0x01c28000 initcall_debug=0 console=ttyS0,115200 loglevel=7 root=/dev/mmcblk0p5 init=/init partitions=UDISK@mmcblk0p1:bootloader@mmcblk0p2:env@mmcblk0p3:boot@mmcblk0p4:system@mmcblk0p5:vendor@mmcblk0p6:misc@mmcblk0p7:recovery@mmcblk0p8:cache@mmcblk0p9:metadata@mmcblk0p10:private@mmcblk0p11:frp@mmcblk0p12:empty@mmcblk0p13:dto@mmcblk0p14:media_data@mmcblk0p15 cma=128M snum=0c001421d445088184e no_console_suspend selinux=1 androidboot.selinux=permissive buildvariant=user hwcfg_p=0x7ffffe00 hwcfg_sz=110 waveform_p=0x7fabaa00 waveform_sz=5526360 ntxfw_p=0x7fab8400 ntxfw_sz=9474 mem=1018M vmalloc=320M androidboot.serialno=23048943,ac1cafa748c341168066df66dd2af473 androidboot.hardware=sun8iw15p1 boot_type=1 dram_clk=792 gpt=1
Bugreport format version: 1.0

**Comment by ChristophHeilmann** [comment]
Manchmal stürzt der Tolino auch ab.

**Comment by ChristophHeilmann** [comment]
Wenn der Tolino das gepatchte Image bootet und nicht abstürzt sind die properties trotzdem falsch:

(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb shell getprop ro.secure
1
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb shell getprop ro.adb.secure
1

**Comment by AaronDewes** [comment]
Dann klappt das Image doch noch nicht ganz, ich Versuche dann Mal noch, die ramdisk zu verbessern, die kann ich nämlich selbst ohne Veränderungen nicht exakt zum gleichen Hash neu erstellen (das boot.img ohne ramdisk-Veränderung schon)

**Comment by ChristophHeilmann** [comment]
Auch fastboot flashing funktioniert nicht:

(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot flashing get_unlock_ability
                                                   FAILED (remote: '')
fastboot: error: Command failed
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot flashing unlock
                                                   FAILED (remote: '')
fastboot: error: Command failed

**Comment by ChristophHeilmann** [comment]
Also das fastboot unter Linux ist kaputt.

(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb shell getprop ro.oem_unlock_supported
1
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb reboot bootloader                                                                     
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# fastboot oem unlock
                                                   FAILED (remote: 'the requst is invalid')
fastboot: error: Command failed

**Comment by ChristophHeilmann** [comment]
Ich frage mich gerade wo denn die fastboot-Befehle landen.

(bullseye)root@localhost:/home/exoriente# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 007: ID 2232:1037 Silicon Motion WebCam SC-03FFM12339N
Bus 003 Device 008: ID 1410:a023 Novatel Wireless Novatel Wireless Gobi3000
Bus 003 Device 002: ID 0424:3503 Microchip Technology, Inc. (formerly SMSC) 
Bus 003 Device 013: ID 1f3a:1010 Allwinner Technology Android device in fastboot mode
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

(bullseye)root@localhost:/home/exoriente# lsusb -v
Bus 003 Device 013: ID 1f3a:1010 Allwinner Technology Android device in fastboot mode
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass       255 Vendor Specific Subclass
  bDeviceProtocol       255 Vendor Specific Protocol
  bMaxPacketSize0        64
  idVendor           0x1f3a Allwinner Technology
  idProduct          0x1010 Android device in fastboot mode
  bcdDevice            2.00
  iManufacturer           5 Android Bootloader Interface
  iProduct                1 USB Developer
  iSerial                 2 Android Fastboot
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0020
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          3 20080411
    bmAttributes         0xc0
      Self Powered
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
bDescriptorType         2
    wTotalLength       0x0020
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          3 20080411
    bmAttributes         0xc0
      Self Powered
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     66 
      bInterfaceProtocol      3 
      iInterface              4 Android Fastboot
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

**Comment by ChristophHeilmann** [comment]
(bullseye)root@localhost:/home/exoriente# fastboot oem device-info
                                                   FAILED (remote: 'fastboot oem operation fail: unknown cmd')
fastboot: error: Command failed

**Comment by ChristophHeilmann** [comment]
Der Tolino antwortet nicht:

(bullseye)root@localhost:/home/exoriente/Downloads/Vision6# adb devices -l
List of devices attached
23048943,ac1cafa748c341168066df66dd2af473 device usb:1-1 product:E70P14_android model:tolino_vision_6 device:E70P14_android transport_id:1
(bullseye)root@localhost:/home/exoriente# fastboot devices -s 23048943,ac1cafa748c341168066df66dd2af473
Android Fastboot        fastboot
(bullseye)root@localhost:/home/exoriente# fastboot oem device-info -s 23048943,ac1cafa748c341168066df66dd2af473
< waiting for 23048943,ac1cafa748c341168066df66dd2af473 >

**Comment by ChristophHeilmann** [comment]
dmesg

[  159.422823] usb 1-1: new high-speed USB device number 3 using xhci-hcd
[  159.438296] usb 1-1: New USB device found, idVendor=4173, idProduct=8000, bcdDevice= 4.40
[  159.438331] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  159.438341] usb 1-1: Product: tolino vision 6
[  159.438352] usb 1-1: Manufacturer: Rakuten Kobo Inc.
[  159.438362] usb 1-1: SerialNumber: 23048943,ac1cafa748c341168066df66dd2af473
[  185.529925] EXT4-fs (mmcblk0p1): re-mounted. Opts: resgid=20119,commit=600,data=ordered
[  238.784407] usb 1-1: USB disconnect, device number 3
[  242.726237] usb 1-1: new high-speed USB device number 4 using xhci-hcd
[  242.742167] usb 1-1: New USB device found, idVendor=1f3a, idProduct=1010, bcdDevice= 2.00
[  242.742226] usb 1-1: New USB device strings: Mfr=5, Product=1, SerialNumber=2
[  242.742272] usb 1-1: Product: USB Developer
[  242.742315] usb 1-1: Manufacturer: Android Bootloader Interface
[  242.742355] usb 1-1: SerialNumber: Android Fastboot

**Comment by ChristophHeilmann** [comment]
Hallo Aaron,

Wenn du bereits einen Vision 6 besitzt höre ich sofort mit dem Spam auf.

**Comment by ChristophHeilmann** [comment]
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6/Bootimage/work-v6# fastboot getvar secure
secure: yes
Das fastboot vom tolino ist die fastboot-Version von uboot mit eingeschränktem Befehlsumfang:
(bullseye)root@localhost:/home/exoriente/Downloads/Vision6/Bootimage/work-v6# fastboot getvar version
version: 0.5
Finished. Total time: 0.003s
siehe https://u-boot.readthedocs.io/en/latest/android/fastboot.html

**Comment by ChristophHeilmann** [comment]
Auf der env-Partition gibt es wohl eine Umgebungsvariable namens "sunxi secure storage".

[130]HELLO! BOOT0 is starting!
[134]boot0 commit : 0a0fa91745d6195e145a4237165c4aea530353c9
 
[152]set pll start
[155]set pll end
[157]rtc[0] value = 0x00000000
[160]rtc[1] value = 0x00000000
[163]rtc[2] value = 0x00000000
[166]rtc[3] value = 0x00000000
[169]rtc[4] value = 0x00000000
[172]rtc[5] value = 0x00000000
[175]DRAM VERSION IS V2_78
[177]the chip id is 0x00000003
[181]the chip id is 0x00000003
[184]the chip id is 0x00000003
[187]the chip id is 0x00000003
[190]the chip id is 0x00000003
[193]chip id check OK
[195]DRAM CLK =648 MHZ
[197]DRAM Type =3 (3:DDR3,4:DDR4,6:LPDDR2,7:LPDDR3)
[202]DRAM zq value: 003b3bfb
[506]IPRD=00930093--PGCR0=00000f7d--PLL=b0003500
[511]para1 = 0000310b,para2 = 08000001
[521]DRAM simple test OK.
[524]card no is 2
[526]sdcard 2 line count 8
[529][mmc]: mmc driver ver 2018-8-11 16:39:00
[533][mmc]: mmc 2 bias 00000004
[542][mmc]: ***Try MMC card %u***
[561][mmc]: MMC 5.0
[563][mmc]: HSDDR52/DDR50 %u bit
[566][mmc]: %u Hz
[568][mmc]: %u MB
[570][mmc]: ***SD/MMC %u init OK!!!***
[654]Loading boot-pkg Succeed(index=0).
[658]Entry_name        = u-boot
[673]Entry_name        = parameter
[677]Entry_name        = monitor
[680]Entry_name        = scp
[689]set arisc reset to de-assert state
[693]Entry_name        = soc-cfg
[697]Entry_name        = dtb
[701]Entry_name        = logo
[704]Ready to disable icache.
[707]Jump to secend Boot.

INFO:    Configuring SPC Controller
NOTICE:  BL3-1: v1.0(debug):c5e8aec
NOTICE:  BL3-1: Built : 14:42:22, Apr 26 2018
NOTICE:  BL3-1 commit: c5e8aec20ca8c6ce31078c5689cbdb1a7352c813

INFO:    BL3-1: Initializing runtime services
ERROR:   Error initializing runtime service tspd_fast
INFO:    BL3-1: Preparing for EL3 exit to normal world
INFO:    BL3-1: Next image address = 0x4a000000
INFO:    BL3-1: Next image spsr = 0x1d3


U-Boot 2014.07 (Jul 22 2019 - 15:32:04) Allwinner Technology 

I2C:   ready
[SCP] :sunxi-arisc driver begin startup 2
[SCP] :arisc version: []
[SCP] :sunxi-arisc driver v1.10 is starting
[0.792]PMU: cpux 1440 Mhz,AXI=720 Mhz

fd650:show_string  boot  8 
Led_Show_650:::acfPStr == boot !!!
Led_Show_650:::pinput[0] == b, data[0] == 0x67
Led_Show_650:::pinput[1] == o, data[1] == 0x63
Led_Show_650:::pinput[2] == o, data[2] == 0x63
Led_Show_650:::pinput[3] == t, data[3] == 0x47
[0.879][cpu1]__clk_enable: clk is null.
[0.879][cpu1]hdmi cec clk enable failed!
[0.880]MMC:	 2
SUNXI SD/MMC: 2
[0.883][cpu1]key emac have not been burned yet
[cpu1]twi_send_slave_addr error
[cpu1]twi_send_slave_addr error
[cpu1]twi_send_slave_addr error
[cpu1]twi_send_slave_addr error
[cpu1]twi_send_slave_addr error
[cpu1]twi_send_slave_addr error
[cpu1]twi_send_slave_addr error
[cpu1]twi_send_slave_addr error
Normal
[cpu1]twi_send_slave_addr error
read item0 copy0
[cpu1]twi_send_slave_addr error
the secure storage item0 copy0 is good
[cpu1]twi_send_slave_addr error
no item name key_burned_flag in the map
[0.919][cpu1]edid all null
[0.922]sunxi storage read fail
[0.927]sunxi secure storage has no flag
[0.931]usb burn from boot
delay time 0
[0.940]usb prepare ok
[1.741]overtime
[1.744]do_burn_from_boot usb : no usb exist
no item name device_unlock in the map
[1.759]sunxi storage read fail
sunxi secure storage has no flag
--------fastboot partitions--------
-total partitions:18-
-name-        -start-       -size-      
UDISK       : bda40000      db1bbc00    
bootloader  : 1000000       2000000     
env         : 3000000       1000000     
boot        : 4000000       2000000     
system      : 6000000       60000000    
vendor      : 66000000      f000000     
misc        : 75000000      1000000     
recovery    : 76000000      2000000     
cache       : 78000000      40000000    
metadata    : b8000000      1000000     
private     : b9000000      1000000     
frp         : ba000000      80000       
empty       : ba080000      f80000      
dtbo        : bb000000      200000      
media_data  : bb200000      1000000     
Reserve0    : bc200000      1000000     
sysrecovery : bd200000      800000      
esm         : bda00000      40000       
-----------------------------------
read item0 copy0
the secure storage item0 copy0 is good
no item name rootwait init in the map
[2.907]sunxi storage read fail
name in map mac
the secure storage item1 copy0 is good
update mac = 04-81-90-71-5C-87
no item name wifi_mac in the map
[2.907]sunxi storage read fail
no item name bt_mac in the map
[2.910]sunxi storage read fail
no item name specialstr in the map
[2.916]sunxi storage read fail
** Unrecognized filesystem type **
Hit any key to stop autoboot:  0 
[3.120]
Starting kernel ...

**Comment by ChristophHeilmann** [comment]
Die default.prop auf der Ramdisk ist nur ein symlink zu /system/etc/prop.default
Wie kann man die System-Partition editieren??
Ich fürchte das war mit dem Root.
